apiVersion: v1
kind: Service
metadata:
  name: voice-transcriber-service
spec:
  selector:
    app: voice-transcriber
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP